version: '3.8'

services:
  gateway:
    build:
      dockerfile: .docker/dev/gateway/Dockerfile
    volumes:
      - ./public:/var/www/html/public:ro
    links:
      - app
    hostname: api
    ports:
      - 8000:8000
    networks:
      - api
      - gateway

  app:
    build:
      dockerfile: .docker/dev/app/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    volumes:
      - ./:/var/www/html
    links:
      - mysql
      - mysql-testing
      - redis
      - mailhog
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - api
      - gateway

  queue:
    build:
      dockerfile: .docker/dev/queue/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    volumes:
      - ./:/var/www/html
    links:
      - mysql
      - redis
      - mailhog
    networks:
      - api

  schedule:
    build:
      dockerfile: .docker/dev/schedule/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    volumes:
      - ./:/var/www/html
    links:
      - mysql
      - redis
      - mailhog
    networks:
      - api

  mysql:
    build:
      dockerfile: .docker/dev/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
      - ./.docker/dev/mysql/dumps/:/var/tmp
    ports:
      - 3306:3306
    networks:
      - api

  mysql-testing:
    build:
      dockerfile: .docker/dev/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - api

  redis:
    build:
      dockerfile: .docker/dev/redis/Dockerfile
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    networks:
      - api

  mailhog:
    build:
      dockerfile: .docker/dev/mailhog/Dockerfile
    ports:
      - 8025:8025
    networks:
      - api

volumes:
  mysql:
    driver: local

  redis:
    driver: local

networks:
  api:
    name: api

  gateway:
    name: gateway
    external: true
